# Generated by Django 4.1.5 on 2023-04-12 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dex", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="prosumer",
            name="billing_account",
            field=models.ForeignKey(
                editable=False,
                help_text="Billing account associated to the prosumer",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prosumers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Billing Account",
            ),
        ),
        migrations.AddField(
            model_name="buyorder",
            name="prosumer",
            field=models.ForeignKey(
                editable=False,
                help_text="Prosumer that created the buy order",
                on_delete=django.db.models.deletion.PROTECT,
                to="dex.prosumer",
                verbose_name="Buyer",
            ),
        ),
    ]
