# Generated by Django 4.1.5 on 2023-04-13 04:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dex", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prosumer",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True,
                help_text="Location of the prosumer",
                srid=4326,
                verbose_name="Location",
            ),
        ),
    ]
