# Generated by Django 4.1.5 on 2023-04-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dex", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellorder",
            name="category",
            field=models.CharField(
                choices=[
                    ("SOLAR", "SOALR"),
                    ("WIND", "WIND"),
                    ("HYDRO", "HYDRO"),
                    ("GEOTHERMAL", "GEOTHERMAL"),
                    ("NUCLEAR", "NUCLEAR"),
                    ("BIOMASS", "BIOMASS"),
                    ("STORAGE", "STORAGE"),
                ],
                default="WIND",
                help_text="Generation Category",
                max_length=255,
                verbose_name="Category",
            ),
            preserve_default=False,
        ),
    ]
