# Generated by Django 4.1.5 on 2023-04-15 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dex", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="order",
            field=models.OneToOneField(
                editable=False,
                help_text="Order that was traded",
                on_delete=django.db.models.deletion.PROTECT,
                to="dex.order",
                verbose_name="Order",
            ),
        ),
    ]
