# Generated by Django 4.1.5 on 2023-04-15 12:40

from django.db import migrations
import sparks.models


class Migration(migrations.Migration):

    dependencies = [
        ("dex", "0003_alter_trade_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="price",
            field=sparks.models.SparksField(
                blank=True,
                help_text="Price of the energy in SPARKS",
                null=True,
                verbose_name="Price (SPARKS)",
            ),
        ),
    ]
