# Generated by Django 4.1.5 on 2023-04-15 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dex", "0004_alter_order_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trade",
            name="energy",
        ),
    ]
