version: '3.9'

services:
  emqx:
    image: emqx/emqx:latest
    restart: always
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-etc:/opt/emqx/etc
      - emqx-log:/opt/emqx/log
    
  telegraf:
    image: telegraf
    restart: always

  influxdb:
    image: influxdb:latest
    restart: always

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  emqx-data:
  emqx-etc:
  emqx-log:

