# Generated by Django 4.1.5 on 2023-04-12 08:03

from django.db import migrations, models
import sparks.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SparksUserWallet",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "deleted",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text="Whether the record is deleted or not (soft-delete)",
                    ),
                ),
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("sparks", sparks.models.SparksField(default=0)),
            ],
            options={
                "verbose_name": "Sparks User Wallet",
                "verbose_name_plural": "Sparks User Wallets",
            },
        ),
    ]
