version: "3.9"

networks:
  default:
    name: dex

volumes:
  db:

services:
  api:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: docker/DevDockerfile
    entrypoint: ["bash", "docker/docker-entrypoint.sh"]
    ports:
      - 9000:9000
    env_file:
      - ./docker/.local.env
    volumes:
      - .:/app

  db:
    image: postgis/postgis:latest
    restart: always
    env_file:
      - ./docker/.local.env
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: always
